AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for EFS FileSystem and Mount Target

Resources:
  MyEFSFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
        - Key: Name
          Value: MyEFSFileSystem
      PerformanceMode: generalPurpose
      Encrypted: true

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.0.0.0/16
      AvailabilityZone: "us-east-1a"
    DependsOn: MyVPC

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref MyVPC
      GroupDescription: Allow http to client host
    DependsOn: MyVPC

  MyEFSMountTarget:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref MyEFSFileSystem
      SubnetId: !Ref MySubnet
      SecurityGroups: 
        - !Ref MySecurityGroup
    DependsOn: 
      - MyEFSFileSystem
      - MySubnet
      - MySecurityGroup